# Generated by Django 5.1.7 on 2026-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='saved_amount',
            new_name='current_amount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
