# Generated by Django 5.2.9 on 2026-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_saved_amount_goal_current_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
